spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    打印sql(删除运行不显示sql语句）
    show-sql: true
    properties:
      hibernate:
#        格式化sql
        format_sql: true
    open-in-view: false
#        端口号（不设置默认为8080）
server:
  port: 8181

